orders/urls.py
from django.urls import path, include
from landing import views
from orders import views

urlpatterns = [
    path('basket_adding/', views.basket_adding, name='basket_adding'),
    path('checkout/', views.checkout, name='checkout'),
]

products/urls.py
from django.urls import path, include
from products import views

urlpatterns = [
    path('<int:product_id>/', views.product, name='product')
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from test_project import settings

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('products/', include('products.urls')),
    path('registration/', include('register.urls')),
    path('', include('landing.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'


class Product(models.Model):
    name = models.CharField(max_length=128)
    contain = models.TextField(blank=True, null=True, default="")
    description = models.TextField(blank=True, null=True, default=None)
    short_description = models.TextField(blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(to=Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')

    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

products/views.py
from django.shortcuts import render
from landing.forms import SubscriberForm
from products.models import *

# Create your views here.


def product(request, product_id):    
    product = Product.objects.get(id=product_id)
    main_image = ProductImage.objects.filter(product=product, is_main=True)[0]

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(session_key)

    return render(request, 'products/product.html', context=locals())

templates/products/product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div id="buket">
    <div class="content">
        <div class="content_padding">
            <div class="head_inside_block">
                <h1 class="head_inside">
                    {{ product.name }}
                </h1>
            </div>
            <div style="padding-bottom: 25px;">
                <form id="form-buying-product" action="{% url 'basket_adding' %}"> {% csrf_token %}
                    <div class="buket_middle">
                        <div class="buket_col">
                            <div class="buket_img">
                                <img srcset="{{ main_image.image.url }}" class="buket_img_main placeholder" alt="{{ product.name }}">
                            </div>
                        </div>
                    </div>
                    <div class="buket_filter">
                        <div class="stop">
                            <div class="buket_col_full">
                                <div class="buket_form buket_form_white_border">
                                    <div class="buket_form_info">
                                        <div class="buket_form_top_desc">
                                            <b>СОСТАВ:</b>
                                            <span>{{ product.contain }}</span>
                                        </div>
                                        <div class="buket_form_top_desc_short">
                                            <b>ОПИСАНИЕ:</b>
                                            <span>
                                                {{ product.description }}
                                            </span>
                                        </div>
                                    </div>
                                    <div class="buket_form_price">
                                        <div class="buket_form_col1">
                                            <p><b>ЦЕНА:</b></p>
                                            <p class="buket_price">
                                                {{ product.price }} ₽
                                            </p>
                                        </div>
                                        <div class="buket_form_col2">
                                            <p><b>Кол-во:</b></p>
                                            <p class="buket_form_input">
                                                <input type="number" name="amount" id="number" class="buket_amount" min="1" max="1001" value="1">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="buket_form_button align-left">
                                        <button type="submit" id="submit-btn" class="btn bg-black buy btn-290" data-product_id = "{{ product.id }}">Добавить в корзину</button>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-lg-6">-->
<!--                {% for image_item in product.productimage_set.all %}-->
<!--                <div class="product-image-item">-->
<!--                    <img src='{{ image_item.image.url }}' class="img-fluid">-->
<!--                </div>-->
<!--                {% endfor %}-->
<!--            </div>-->
<!--            <div class="col-lg-6">-->
<!--                <h1 class="text-center">-->
<!--                    {{ product.name }}-->
<!--                </h1>-->
<!--                <div class="">-->
<!--                    <p>-->
<!--                        Price: {{ product.price }}-->
<!--                    </p>-->
<!--                </div>-->

<!--                &lt;!&ndash;Nav tabs&ndash;&gt;-->
<!--                <ul class="nav nav-tabs" id="myTab" role="tablist">-->
<!--                  <li class="nav-item">-->
<!--                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#description" role="tab" aria-controls="home" aria-selected="true">-->
<!--                        Описание-->
<!--                    </a>-->
<!--                  </li>-->
<!--                  <li class="nav-item">-->
<!--                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#delivery" role="tab" aria-controls="profile" aria-selected="false">-->
<!--                        Доставка-->
<!--                    </a>-->
<!--                  </li>-->
<!--                  <li class="nav-item">-->
<!--                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>-->
<!--                  </li>-->
<!--                </ul>-->

<!--&lt;!&ndash;                Tab content&ndash;&gt;-->
<!--                <div class="tab-content product-description-tabs" id="myTabContent">-->
<!--                  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="home-tab">-->
<!--                      {{ product.description }}-->
<!--                  </div>-->
<!--                  <div class="tab-pane fade" id="delivery" role="tabpanel" aria-labelledby="profile-tab">-->
<!--                      <h3>Как мы делаем доставку?</h3>-->
<!--                  </div>-->
<!--                  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>-->
<!--                </div>-->
<!--                <div>-->
<!--                    <form id="form-buying-product" class="form-inline" action="{% url 'basket_adding' %}"> {% csrf_token %}-->
<!--                        <div class="form-group">-->
<!--                            <input type="number" class="form-control" name="number" id="number">-->
<!--                        </div>-->
<!--                        <div class="form-group">-->
<!--                            <button class="btn btn-success btn-buy" type="submit" id="submit-btn"-->
<!--                                    data-product_id = "{{ product.id }}">-->
<!--                                Купить-->
<!--                            </button>-->
<!--                        </div>-->
<!--                    </form>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    
{% endblock %}